.F..
======================================================================
FAIL: test_should_return_fizz_for_multiples_of_three (test_fizzbuzz.TestFizzBuzz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_fizzbuzz.py", line 17, in test_should_return_fizz_for_multiples_of_three
    self.assertEqual("Fizz", Fizzbuzz().fizzbuzz(9))
AssertionError: 'Fizz' != '9'
- Fizz
+ 9


----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (failures=1)
